// One-off generator: decode the two pasted /w#<base64> preset designs, strip the
// author's identity (lfmUser/sessionKey/apiKey), and emit a clean preset-data
// module. Run with: bun scripts/gen-presets.ts
import { readFileSync, writeFileSync } from "fs";

function scan(file: string): string | null {
  const raw = readFileSync(file, "utf8").replace(/\s+/g, "");
  const bad: { i: number; c: string; code: number; ctx: string }[] = [];
  for (let i = 0; i < raw.length; i++) {
    if (!/[A-Za-z0-9_-]/.test(raw[i])) {
      bad.push({ i, c: raw[i], code: raw.charCodeAt(i), ctx: raw.slice(Math.max(0, i - 14), i + 14) });
    }
  }
  if (bad.length) {
    console.log(`\n${file}: ${bad.length} INVALID char(s):`);
    for (const b of bad.slice(0, 40)) console.log(`  @${b.i} U+${b.code.toString(16)} '${b.c}' ...${b.ctx}...`);
    return null;
  }
  return raw;
}

function decode(b64url: string): any {
  const b64 = b64url.replace(/-/g, "+").replace(/_/g, "/");
  const json = Buffer.from(b64, "base64").toString("utf8");
  return JSON.parse(json);
}

const targets = [
  { name: "Minimalist", file: "tmp_min.txt" },
  { name: "Modern Card", file: "tmp_mod.txt" },
];

const out: { name: string; config: any }[] = [];
let ok = true;
for (const t of targets) {
  const clean = scan(t.file);
  if (!clean) { ok = false; continue; }
  const cfg = decode(clean);
  // strip identity
  cfg.lfmUser = "";
  cfg.sessionKey = null;
  cfg.apiKey = null;
  // normalize v2 elements to the current schema (older exports may predate fields)
  const els = cfg.v2?.elements ?? {};
  for (const k of Object.keys(els)) if (els[k].fillOpacity === undefined) els[k].fillOpacity = 100;
  console.log(
    `${t.name}: version=${cfg.version} bgFill=${cfg.v2?.elements?.background?.fill} bgW=${cfg.v2?.elements?.background?.w} titleColor=${cfg.v2?.elements?.title?.color} titleSize=${cfg.theme?.textSize?.title}`,
  );
  out.push({ name: t.name, config: cfg });
}

if (!ok) {
  console.log("\nFix the invalid characters above and re-run.");
  process.exit(1);
}

const header = `// AUTO-GENERATED by scripts/gen-presets.ts from the editor's /w#<base64> exports.
// Decoded v2 designs with identity (lfmUser/sessionKey/apiKey) stripped. Do not edit by hand.
import type { WidgetConfig } from "./config";

export const PRESET_DATA: { name: string; config: WidgetConfig }[] = `;
writeFileSync("apps/web/src/lib/preset-data.ts", header + JSON.stringify(out, null, 2) + ";\n");
console.log("\nWrote apps/web/src/lib/preset-data.ts");
