// Replace one built-in preset's config with a raw JSON export (e.g. from the
// editor's dev "Copy JSON" button), applying the same identity-strip +
// normalization as gen-presets.ts, and rewrite preset-data.ts in the same
// generated format.
//
// Usage: bun scripts/set-preset.ts "<preset name>" <path-to-config.json>
import { readFileSync, writeFileSync } from "fs";
import { PRESET_DATA } from "../apps/web/src/lib/preset-data";

const [name, file] = process.argv.slice(2);
if (!name || !file) {
  console.error('Usage: bun scripts/set-preset.ts "<preset name>" <path-to-config.json>');
  console.error(`Known presets: ${PRESET_DATA.map((p) => p.name).join(", ")}`);
  process.exit(1);
}
if (!PRESET_DATA.some((p) => p.name === name)) {
  console.error(`Preset "${name}" not found. Known: ${PRESET_DATA.map((p) => p.name).join(", ")}`);
  process.exit(1);
}

const cfg = JSON.parse(readFileSync(file, "utf8"));

// strip identity (same as gen-presets.ts)
cfg.lfmUser = "";
cfg.sessionKey = null;
cfg.apiKey = null;
// normalize v2 elements to the current schema (older exports may predate fields)
const els = cfg.v2?.elements ?? {};
for (const k of Object.keys(els)) if (els[k].fillOpacity === undefined) els[k].fillOpacity = 100;

console.log(
  `${name}: version=${cfg.version} bgFill=${cfg.v2?.elements?.background?.fill} bgW=${cfg.v2?.elements?.background?.w} titleColor=${cfg.v2?.elements?.title?.color} titleSize=${cfg.theme?.textSize?.title}`,
);

const out = PRESET_DATA.map((p) => (p.name === name ? { name: p.name, config: cfg } : p));

const header = `// AUTO-GENERATED by scripts/gen-presets.ts from the editor's /w#<base64> exports.
// Decoded v2 designs with identity (lfmUser/sessionKey/apiKey) stripped. Do not edit by hand.
import type { WidgetConfig } from "./config";

export const PRESET_DATA: { name: string; config: WidgetConfig }[] = `;
writeFileSync("apps/web/src/lib/preset-data.ts", header + JSON.stringify(out, null, 2) + ";\n");
console.log("Wrote apps/web/src/lib/preset-data.ts");
