/** Curated Google Fonts offered in the editor font pickers. */
export const GOOGLE_FONTS = [
  "Inter",
  "Roboto",
  "Open Sans",
  "Lato",
  "Montserrat",
  "Poppins",
  "Nunito",
  "Raleway",
  "Oswald",
  "Work Sans",
  "Rubik",
  "DM Sans",
  "Space Grotesk",
  "Quicksand",
  "Josefin Sans",
  "Comfortaa",
  "Bebas Neue",
  "Merriweather",
  "Playfair Display",
  "Source Sans 3",
  "Ubuntu",
  "Fira Sans",
  "PT Sans",
  "Dancing Script",
  "Pacifico",
  "Lobster",
  "Caveat",
] as const;
