// src/utils/keywords.ts
// A large set of SEO keywords/phrases for streamer music widget discovery
// Keep them lowercase and focused; meta keywords are largely ignored by search engines
// today, but some platforms still read them. This list is also useful for tags elsewhere.

export const KEYWORDS: string[] = [
  "last.fm",
  "lastfm",
  "last fm",
  "scrobble",
  "scrobbles",
  "scrobbling",
  "now playing",
  "np",
  "now playing overlay",
  "now playing widget",
  "obs",
  "obs overlay",
  "obs browser source",
  "obs widget",
  "browser source",
  "stream overlay",
  "stream widgets",
  "stream widget",
  "streaming",
  "streamer",
  "streamers",
  "twitch",
  "twitch overlay",
  "twitch widget",
  "twitch music overlay",
  "twitch now playing",
  "youtube",
  "youtube live",
  "youtube streaming",
  "kick streaming",
  "kick overlay",
  "facebook gaming",
  "trovo",
  "x",
  "twitter",
  "tiktok live",
  "restream",
  "streamlabs",
  "streamlabs obs",
  "streamelements",
  "xsplit",
  "vmix",
  "prism live",
  "elgato",
  "elgato stream deck",
  "overlay graphics",
  "overlay design",
  "overlay template",
  "music overlay",
  "music widget",
  "music banner",
  "music ticker",
  "ticker",
  "scrolling text",
  "marquee",
  "marquee text",
  "marquee scrolling",
  "text ticker",
  "song",
  "songs",
  "track",
  "tracks",
  "title",
  "artist",
  "artists",
  "album",
  "albums",
  "album art",
  "cover art",
  "artwork",
  "album cover",
  "cover image",
  "dominant color",
  "color from image",
  "color from album art",
  "auto color",
  "auto theme",
  "auto theming",
  "contrast",
  "wcag",
  "readable text",
  "high contrast",
  "palette",
  "color palette",
  "accent color",
  "accent",
  "background color",
  "theming",
  "theme",
  "themes",
  "dark mode",
  "light mode",
  "typography",
  "font",
  "fonts",
  "google fonts",
  "inter font",
  "poppins font",
  "roboto font",
  "montserrat font",
  "nunito font",
  "oswald font",
  "lato font",
  "css",
  "tailwind",
  "tailwindcss",
  "tailwind css",
  "react",
  "next.js",
  "nextjs",
  "typescript",
  "javascript",
  "node",
  "node.js",
  "api route",
  "next api",
  "edge",
  "client side",
  "server side",
  "ssr",
  "sse",
  "websocket",
  "fetch",
  "cors",
  "image proxy",
  "image blob",
  "blob url",
  "object url",
  "canvas",
  "canvas color extract",
  "center crop",
  "image analysis",
  "dominant color extract",
  "average color",
  "color detection",
  "hex color",
  "rgb color",
  "luminance",
  "contrast ratio",
  "wcag contrast",
  "accessibility",
  "a11y",
  "readability",
  "progress bar",
  "music progress",
  "timeline",
  "music timeline",
  "live music",
  "music stream",
  "music streaming",
  "playing now",
  "currently playing",
  "song title",
  "song artist",
  "song album",
  "cover",
  "record sleeve",
  "vinyl",
  "cd cover",
  "mp3",
  "flac",
  "ogg",
  "metadata",
  "id3",
  "music metadata",
  "playlist",
  "playlists",
  "dj",
  "dj overlay",
  "radio",
  "internet radio",
  "podcast",
  "podcasting",
  "broadcaster",
  "broadcasting",
  "gaming",
  "gaming overlay",
  "gaming stream",
  "just chatting",
  "lofi",
  "hip hop",
  "edm",
  "electronic",
  "house music",
  "techno",
  "trance",
  "dubstep",
  "rock",
  "pop",
  "jazz",
  "blues",
  "soul",
  "r&b",
  "country",
  "classical",
  "orchestral",
  "soundtrack",
  "anime",
  "kpop",
  "jpop",
  "metal",
  "punk",
  "indie",
  "alt",
  "ambient",
  "chill",
  "study music",
  "focus music",
  "work music",
  "background music",
  "playlist overlay",
  "music card",
  "music card widget",
  "music panel",
  "now playing panel",
  "custom overlay",
  "custom widgets",
  "customization",
  "customizable",
  "lightweight",
  "fast",
  "low latency",
  "responsive",
  "modern ui",
  "simple ui",
  "clean ui",
  "minimal ui",
  "design",
  "ui design",
  "ux",
  "ui",
  "open source",
  "free",
  "free widget",
  "free overlay",
  "free tool",
  "github",
  "github project",
  "vercel",
  "vercel deploy",
  "deploy",
  "deployment",
  "next deploy",
  "edge runtime",
  "ssg",
  "seo",
  "social meta",
  "open graph",
  "og image",
  "twitter card",
  "meta tags",
  "json-ld",
  "schema.org",
  "softwareapplication",
  "structured data",
  "sitemap",
  "robots.txt",
  "canonical url",
  "canonical link",
  "web app",
  "pwa",
  "progressive web app",
  "widget link",
  "share link",
  "stream link",
  "obs link",
  "browser link",
  "embed",
  "embed overlay",
  "overlay embed",
  "iframe",
  "overlay scene",
  "scene",
  "scene collection",
  "source",
  "source settings",
  "link settings",
  "config",
  "configuration",
  "settings",
  "editor",
  "preview",
  "live preview",
  "marquee speed",
  "marquee gap",
  "per-text speed",
  "per-text gap",
  "scroll speed",
  "scroll gap",
  "text gap",
  "text offset",
  "x offset",
  "y offset",
  "align left",
  "align center",
  "align right",
  "text align",
  "art position left",
  "art position right",
  "art position top",
  "album art left",
  "album art right",
  "album art top",
  "show album art",
  "hide album art",
  "image proxy route",
  "proxy image",
  "cors proxy",
  "image loading",
  "image reliability",
  "blob rendering",
  "broken image hide",
  "fallback image",
  "placeholder image",
  "lfm username",
  "lastfm username",
  "lastfm account",
  "private lastfm",
  "public lastfm",
  "session key",
  "lastfm api",
  "lastfm api route",
  "recent tracks",
  "track info",
  "lfm now playing",
  "now playing api",
  "polling",
  "poll interval",
  "5s poll",
  "request cache",
  "etag",
  "cache control",
  "http cache",
  "debounce",
  "throttle",
  "smoothing",
  "fade",
  "transition",
  "css transition",
  "gpu acceleration",
  "will-change",
  "performance",
  "perf",
  "fps",
  "obs performance",
  "low cpu",
  "low memory",
  "memory footprint",
  "stability",
  "reliability",
  "robust",
  "resilient",
  "error handling",
  "error boundary",
  "error retry",
  "fallback",
  "safety",
  "security",
  "rate limit",
  "api key",
  "secret",
  "env",
  "environment",
  "config import",
  "config share",
  "share url",
  "shareable link",
  "copy link",
  "paste settings",
  "copy settings",
  "editor import",
  "widget url",
  "widget hash",
  "hash config",
  "base64 config",
  "b64",
  "compress",
  "minify",
  "json",
  "json config",
  "merge defaults",
  "deep merge",
  "partial config",
  "layout size",
  "width",
  "height",
  "art size",
  "rounded corners",
  "border radius",
  "shadow",
  "glassmorphism",
  "neumorphism",
  "skeuomorphism",
  "minimalism",
  "flat design",
  "gradient",
  "gradient background",
  "blur",
  "backdrop",
  "backdrop blur",
  "transparency",
  "transparent background",
  "paused mode",
  "transparent when paused",
  "paused label",
  "not playing label",
  "song paused",
  "music paused",
  "history",
  "track history",
  "play history",
  "recent plays",
  "recently played",
  "song history",
  "duration",
  "elapsed",
  "remaining",
  "time left",
  "uptime",
  "counter",
  "timer",
  "update frequency",
  "poll ms",
  "five seconds",
  "real time",
  "live",
  "live overlay",
  "live widget",
  "stream toolkit",
  "stream tools",
  "creator tools",
  "content creator",
  "vtuber",
  "music streamer",
  "radio dj",
  "podcaster",
  "indie dev",
  "open-source",
  "opensource",
  "github repo",
  "issues",
  "pull request",
  "contribution",
  "contributing",
  "license",
  "mit license",
  "vercel edge",
  "vercel project",
  "deployment guide",
  "setup guide",
  "how to",
  "tutorial",
  "documentation",
  "readme",
  "changelog",
  "release",
  "version",
  "semantic versioning",
  "semver",
  "linting",
  "eslint",
  "prettier",
  "formatting",
  "typescript types",
  "strict types",
  "type safety",
  "hooks",
  "react hooks",
  "useeffect",
  "usememo",
  "usestate",
  "ref",
  "useref",
  "resize observer",
  "intersection observer",
  "animation",
  "css animation",
  "keyframes",
  "loop",
  "infinite",
  "seamless scroll",
  "text overflow",
  "ellipsis",
  "white-space nowrap",
  "nowrap",
  "gap",
  "distance",
  "duration",
  "speed",
  "px per second",
  "px/s",
  "gap px",
  "grid layout",
  "css grid",
  "flexbox",
  "display grid",
  "justify",
  "align",
  "center",
  "left",
  "right",
  "top",
  "bottom",
  "z-index",
  "stacking",
  "font weight",
  "bold",
  "italic",
  "underline",
  "strikethrough",
  "text decoration",
  "line height",
  "letter spacing",
  "tracking",
  "kerning",
  "font size",
  "title size",
  "artist size",
  "album size",
  "meta size",
  "meta text",
  "status text",
  "paused text",
  "label",
  "capabilities",
  "features",
  "options",
  "controls",
  "ui controls",
  "toggle",
  "checkbox",
  "range input",
  "slider",
  "color input",
  "color picker",
  "hex picker",
  "accent toggle",
  "use accent",
  "text color",
  "per-text color",
  "unified color",
  "global color",
  "bg enabled",
  "background on",
  "background off",
  "show art",
  "hide art",
  "art size control",
  "text offsets",
  "offset control",
  "scroll trigger width",
  "trigger width",
  "min width",
  "content width",
  "overflow",
  "measure text",
  "measure width",
  "resize",
  "responsive layout",
  "grid columns",
  "grid rows",
  "gap size",
  "spacing",
  "padding",
  "border",
  "rounded",
  "radius",
  "corner radius",
  "widget card",
  "card ui",
  "music card overlay",
  "music info",
  "track info overlay",
  "lfm connect",
  "lastfm connect",
  "auth",
  "authentication",
  "session",
  "session storage",
  "local storage",
  "clipboard",
  "copy",
  "paste",
  "share",
  "open in editor",
  "open widget",
  "public widget",
  "private preview",
  "private scrobble",
  "public profile",
  "profile",
  "username",
  "user name",
  "handle",
  "channel",
  "channel overlay",
  "brand",
  "branding",
  "identity",
  "style guide",
  "color system",
  "design system",
  "themable",
  "themeable",
  "skin",
  "skins",
  "templates",
  "presets",
  "preset",
  "defaults",
  "default theme",
  "custom theme",
  "import settings",
  "export settings",
  "configuration url",
  "url hash",
  "hash state",
  "state in url",
  "deep link",
  "deeplink",
  "linkable",
  "shareable",
  "portable",
  "simple setup",
  "quick start",
  "getting started",
  "guide",
  "how-to",
  "tips",
  "best practices",
  "troubleshooting",
  "faq",
  "help",
  "support",
  "community",
  "discord",
  "reddit",
  "forum",
  "feedback",
  "feature request",
  "bug report",
  "issue",
  "fix",
  "patch",
  "update",
  "optimize",
  "optimation",
  "optimization",
  "refactor",
  "cleanup",
  "staging",
  "production",
  "env var",
  "environment variable",
  "dotenv",
  "ci",
  "cd",
  "ci/cd",
  "pipeline",
  "build",
  "build cache",
  "incremental",
  "hot reload",
  "fast refresh",
  "dev server",
  "devtools",
  "debug",
  "log",
  "console",
  "privacy",
  "gdpr",
  "cookie",
  "cookie-less",
  "analytics",
  "tracking",
  "utm",
  "campaign",
  "marketing",
  "discoverability",
  "indexing",
  "crawl",
  "crawler",
  "bot",
  "search engine",
  "seo optimization",
  "keyword",
  "keywords",
  "tags",
  "meta keywords",
  "meta description",
  "title tag",
  "og tags",
  "twitter tags",
  "link preview",
  "unfurl",
  "card preview",
  "share card",
  "preview card",
];

export const KEYWORDS_META = KEYWORDS.join(", ");
