// AUTO-GENERATED by scripts/gen-presets.ts from the editor's /w#<base64> exports.
// Decoded v2 designs with identity (lfmUser/sessionKey/apiKey) stripped. Do not edit by hand.
import type { WidgetConfig } from "./config";

export const PRESET_DATA: { name: string; config: WidgetConfig }[] = [
  {
    "name": "Minimalist",
    "config": {
      "lfmUser": "",
      "fallbackAccent": "#1db954",
      "theme": {
        "bg": "#000000CC",
        "accent": "#1db954",
        "autoFromArt": true,
        "autoTargets": {
          "title": false,
          "artist": true,
          "album": false,
          "meta": false
        },
        "font": "Inter",
        "text": {
          "title": "#ffffff",
          "artist": "accent",
          "album": "#cfcfcf",
          "meta": "#bdbdbd",
          "duration": "#a0a0a0"
        },
        "textSize": {
          "title": 33,
          "artist": 19,
          "album": 12,
          "meta": 12,
          "duration": 11
        },
        "textStyle": {
          "title": {
            "italic": false,
            "underline": false,
            "bold": true,
            "strike": false
          },
          "artist": {
            "italic": false,
            "underline": false,
            "bold": false,
            "strike": false
          },
          "album": {
            "italic": false,
            "underline": false,
            "bold": false,
            "strike": false
          },
          "meta": {
            "italic": false,
            "underline": false,
            "bold": false,
            "strike": false
          },
          "duration": {
            "italic": false,
            "underline": false,
            "bold": false,
            "strike": false
          }
        },
        "textTransform": {
          "title": "none",
          "artist": "uppercase",
          "album": "none",
          "meta": "none",
          "duration": "none"
        },
        "textFont": {
          "title": "Montserrat",
          "artist": "Poppins"
        },
        "dropShadow": {
          "enabled": true,
          "blur": 19,
          "intensity": 15,
          "offsetX": 2,
          "offsetY": 2,
          "useOppositeColor": true,
          "customColor": "#000000",
          "targets": {
            "text": true,
            "albumArt": true,
            "progressBar": true,
            "background": false
          },
          "perText": {
            "title": {
              "enabled": true,
              "useOppositeColor": true
            },
            "artist": {
              "enabled": true,
              "useOppositeColor": true
            },
            "album": {
              "enabled": true,
              "useOppositeColor": true
            },
            "meta": {
              "enabled": true,
              "useOppositeColor": true
            },
            "duration": {
              "enabled": true,
              "useOppositeColor": true
            }
          }
        },
        "bgEnabled": false
      },
      "layout": {
        "w": 420,
        "h": 130,
        "showArt": true,
        "align": "left",
        "artSize": 68,
        "artPosition": "left",
        "scrollTriggerWidth": 180,
        "textGap": 2,
        "backgroundRadius": 16,
        "artRadius": 6,
        "progressWidth": 0,
        "progressOffset": {
          "x": 0,
          "y": 0
        },
        "textOffset": {
          "title": {
            "x": 0,
            "y": 0
          },
          "artist": {
            "x": 0,
            "y": 0
          },
          "album": {
            "x": 0,
            "y": 0
          },
          "meta": {
            "x": 0,
            "y": 0
          },
          "duration": {
            "x": 0,
            "y": 0
          }
        }
      },
      "marquee": {
        "speedPxPerSec": 24,
        "gapPx": 32
      },
      "fields": {
        "title": true,
        "artist": true,
        "album": false,
        "progress": false,
        "duration": false,
        "history": 50,
        "pausedMode": "transparent",
        "pausedText": "Paused",
        "durationFormat": "both",
        "showDurationOnProgress": true,
        "showDurationAsText": false
      },
      "version": 2,
      "v2": {
        "elements": {
          "background": {
            "visible": true,
            "x": 0,
            "y": 0,
            "w": 420,
            "h": 135,
            "z": 0,
            "color": "#000000CC",
            "fill": "none",
            "anchor": "left",
            "radius": 16,
            "shadow": {
              "enabled": false,
              "blur": 19,
              "intensity": 15,
              "offsetX": 2,
              "offsetY": 2,
              "useOppositeColor": true,
              "customColor": "#000000"
            },
            "scroll": {
              "enabled": false,
              "direction": "left",
              "speedPxPerSec": 24,
              "gapPx": 32
            },
            "snapX": null,
            "snapY": null,
            "fillOpacity": 100
          },
          "art": {
            "visible": true,
            "x": 12,
            "y": 31,
            "w": 68,
            "h": 68,
            "z": 1,
            "color": "#ffffff",
            "fill": "color",
            "anchor": "left",
            "radius": 6,
            "shadow": {
              "enabled": true,
              "blur": 19,
              "intensity": 15,
              "offsetX": 2,
              "offsetY": 2,
              "useOppositeColor": true,
              "customColor": "#000000"
            },
            "scroll": {
              "enabled": false,
              "direction": "left",
              "speedPxPerSec": 24,
              "gapPx": 32
            },
            "snapX": null,
            "snapY": null,
            "fillOpacity": 100
          },
          "title": {
            "visible": true,
            "x": 91,
            "y": 28,
            "w": 307,
            "h": 43,
            "z": 2,
            "color": "#ffffff",
            "fill": "color",
            "anchor": "left",
            "shadow": {
              "enabled": true,
              "blur": 19,
              "intensity": 15,
              "offsetX": 2,
              "offsetY": 2,
              "useOppositeColor": true,
              "customColor": "#000000"
            },
            "scroll": {
              "enabled": true,
              "direction": "left",
              "speedPxPerSec": 24,
              "gapPx": 32
            },
            "snapX": null,
            "snapY": null,
            "radius": 0,
            "fillOpacity": 100
          },
          "artist": {
            "visible": true,
            "x": 92,
            "y": 71,
            "w": null,
            "h": null,
            "z": 3,
            "color": "accent",
            "fill": "color",
            "anchor": "left",
            "shadow": {
              "enabled": false,
              "blur": 19,
              "intensity": 15,
              "offsetX": 2,
              "offsetY": 2,
              "useOppositeColor": true,
              "customColor": "#000000"
            },
            "scroll": {
              "enabled": true,
              "direction": "left",
              "speedPxPerSec": 24,
              "gapPx": 32
            },
            "snapX": null,
            "snapY": null,
            "radius": 0,
            "fillOpacity": 100
          },
          "album": {
            "visible": false,
            "x": 92,
            "y": 84,
            "w": null,
            "h": null,
            "z": 4,
            "color": "#cfcfcf",
            "fill": "color",
            "anchor": "left",
            "shadow": {
              "enabled": true,
              "blur": 19,
              "intensity": 15,
              "offsetX": 2,
              "offsetY": 2,
              "useOppositeColor": true,
              "customColor": "#000000"
            },
            "scroll": {
              "enabled": true,
              "direction": "left",
              "speedPxPerSec": 24,
              "gapPx": 32
            },
            "snapX": null,
            "snapY": null,
            "radius": 0,
            "fillOpacity": 100
          },
          "progress": {
            "visible": false,
            "x": 92,
            "y": 90,
            "w": 316,
            "h": 6,
            "z": 5,
            "color": "accent",
            "fill": "color",
            "anchor": "left",
            "shadow": {
              "enabled": true,
              "blur": 19,
              "intensity": 15,
              "offsetX": 2,
              "offsetY": 2,
              "useOppositeColor": true,
              "customColor": "#000000"
            },
            "scroll": {
              "enabled": false,
              "direction": "left",
              "speedPxPerSec": 24,
              "gapPx": 32
            },
            "radius": 4,
            "snapX": null,
            "snapY": null,
            "fillOpacity": 100
          },
          "duration": {
            "visible": false,
            "x": 92,
            "y": 104,
            "w": null,
            "h": null,
            "z": 6,
            "color": "#a0a0a0",
            "fill": "color",
            "anchor": "left",
            "shadow": {
              "enabled": true,
              "blur": 19,
              "intensity": 15,
              "offsetX": 2,
              "offsetY": 2,
              "useOppositeColor": true,
              "customColor": "#000000"
            },
            "scroll": {
              "enabled": true,
              "direction": "left",
              "speedPxPerSec": 24,
              "gapPx": 32
            },
            "snapX": null,
            "snapY": null,
            "radius": 0,
            "fillOpacity": 100
          }
        },
        "switchAnim": {
          "type": "fade",
          "direction": "up",
          "durationMs": 350,
          "easing": "cubicOut"
        }
      },
      "sessionKey": null,
      "apiKey": null
    }
  },
  {
    "name": "Modern Card",
    "config": {
      "lfmUser": "",
      "fallbackAccent": "#1db954",
      "theme": {
        "bg": "#797777",
        "accent": "#1db954",
        "autoFromArt": true,
        "autoTargets": {
          "title": false,
          "artist": true,
          "album": false,
          "meta": false
        },
        "font": "Inter",
        "text": {
          "title": "accent",
          "artist": "accent",
          "album": "#cfcfcf",
          "meta": "#bdbdbd",
          "duration": "accent"
        },
        "textSize": {
          "title": 42,
          "artist": 22,
          "album": 17,
          "meta": 12,
          "duration": 15
        },
        "textStyle": {
          "title": {
            "italic": false,
            "underline": false,
            "bold": true,
            "strike": false
          },
          "artist": {
            "italic": false,
            "underline": false,
            "bold": false,
            "strike": false
          },
          "album": {
            "italic": true,
            "underline": false,
            "bold": false,
            "strike": false
          },
          "meta": {
            "italic": false,
            "underline": false,
            "bold": false,
            "strike": false
          },
          "duration": {
            "italic": true,
            "underline": false,
            "bold": false,
            "strike": false
          }
        },
        "textTransform": {
          "title": "none",
          "artist": "none",
          "album": "none",
          "meta": "none",
          "duration": "none"
        },
        "textFont": {
          "title": "Poppins",
          "artist": "Poppins",
          "duration": "Nunito"
        },
        "dropShadow": {
          "enabled": false,
          "blur": 4,
          "intensity": 50,
          "offsetX": 2,
          "offsetY": 2,
          "useOppositeColor": true,
          "customColor": "#000000",
          "targets": {
            "text": true,
            "albumArt": true,
            "progressBar": true,
            "background": false
          },
          "perText": {
            "title": {
              "enabled": true,
              "useOppositeColor": true
            },
            "artist": {
              "enabled": true,
              "useOppositeColor": true
            },
            "album": {
              "enabled": true,
              "useOppositeColor": true
            },
            "meta": {
              "enabled": true,
              "useOppositeColor": true
            },
            "duration": {
              "enabled": true,
              "useOppositeColor": true
            }
          }
        },
        "bgEnabled": true
      },
      "layout": {
        "w": 310,
        "h": 130,
        "showArt": true,
        "align": "left",
        "artSize": 72,
        "artPosition": "left",
        "scrollTriggerWidth": 180,
        "textGap": 2,
        "backgroundRadius": 16,
        "artRadius": 9,
        "progressWidth": 0,
        "progressOffset": {
          "x": 0,
          "y": 0
        },
        "textOffset": {
          "title": {
            "x": 0,
            "y": 3
          },
          "artist": {
            "x": 0,
            "y": -5
          },
          "album": {
            "x": 0,
            "y": 0
          },
          "meta": {
            "x": 0,
            "y": 0
          },
          "duration": {
            "x": 0,
            "y": -10
          }
        }
      },
      "marquee": {
        "speedPxPerSec": 24,
        "gapPx": 32
      },
      "fields": {
        "title": true,
        "artist": true,
        "album": false,
        "progress": false,
        "duration": true,
        "history": 50,
        "pausedMode": "label",
        "pausedText": "Paused",
        "durationFormat": "both",
        "showDurationOnProgress": true,
        "showDurationAsText": true
      },
      "version": 2,
      "v2": {
        "elements": {
          "background": {
            "visible": true,
            "x": 0,
            "y": 0,
            "w": 518,
            "h": 130,
            "z": 0,
            "color": "#797777",
            "fill": "art",
            "anchor": "left",
            "radius": 0,
            "shadow": {
              "enabled": false,
              "blur": 4,
              "intensity": 50,
              "offsetX": 2,
              "offsetY": 2,
              "useOppositeColor": true,
              "customColor": "#000000"
            },
            "scroll": {
              "enabled": false,
              "direction": "left",
              "speedPxPerSec": 24,
              "gapPx": 32
            },
            "snapX": null,
            "snapY": null,
            "fillOpacity": 100
          },
          "art": {
            "visible": true,
            "x": 8,
            "y": 10,
            "w": 110,
            "h": 110,
            "z": 1,
            "color": "#ffffff",
            "fill": "color",
            "anchor": "left",
            "radius": 9,
            "shadow": {
              "enabled": true,
              "blur": 4,
              "intensity": 50,
              "offsetX": 2,
              "offsetY": 2,
              "useOppositeColor": true,
              "customColor": "#000000"
            },
            "scroll": {
              "enabled": false,
              "direction": "left",
              "speedPxPerSec": 24,
              "gapPx": 32
            },
            "snapX": null,
            "snapY": {
              "to": "background",
              "myEdge": "center",
              "toEdge": "center",
              "offset": 0
            },
            "fillOpacity": 100
          },
          "title": {
            "visible": true,
            "x": 127,
            "y": 2,
            "w": 383,
            "h": 58,
            "z": 2,
            "color": "accent",
            "fill": "color",
            "anchor": "left",
            "shadow": {
              "enabled": true,
              "blur": 4,
              "intensity": 50,
              "offsetX": 2,
              "offsetY": 2,
              "useOppositeColor": true,
              "customColor": "#000000"
            },
            "scroll": {
              "enabled": true,
              "direction": "left",
              "speedPxPerSec": 24,
              "gapPx": 32
            },
            "snapX": null,
            "snapY": null,
            "radius": 0,
            "fillOpacity": 100
          },
          "artist": {
            "visible": true,
            "x": 132,
            "y": 48,
            "w": 378,
            "h": null,
            "z": 3,
            "color": "accent",
            "fill": "color",
            "anchor": "left",
            "shadow": {
              "enabled": true,
              "blur": 4,
              "intensity": 50,
              "offsetX": 2,
              "offsetY": 2,
              "useOppositeColor": true,
              "customColor": "#000000"
            },
            "scroll": {
              "enabled": true,
              "direction": "left",
              "speedPxPerSec": 24,
              "gapPx": 32
            },
            "snapX": null,
            "snapY": null,
            "radius": 0,
            "fillOpacity": 100
          },
          "album": {
            "visible": true,
            "x": 129,
            "y": 74,
            "w": 382,
            "h": 23,
            "z": 4,
            "color": "#cfcfcf",
            "fill": "color",
            "anchor": "left",
            "shadow": {
              "enabled": true,
              "blur": 4,
              "intensity": 50,
              "offsetX": 2,
              "offsetY": 2,
              "useOppositeColor": true,
              "customColor": "#000000"
            },
            "scroll": {
              "enabled": true,
              "direction": "left",
              "speedPxPerSec": 24,
              "gapPx": 32
            },
            "snapX": null,
            "snapY": null,
            "radius": 0,
            "fillOpacity": 100
          },
          "progress": {
            "visible": false,
            "x": 96,
            "y": 89,
            "w": 202,
            "h": 6,
            "z": 5,
            "color": "accent",
            "fill": "color",
            "anchor": "left",
            "shadow": {
              "enabled": false,
              "blur": 4,
              "intensity": 50,
              "offsetX": 2,
              "offsetY": 2,
              "useOppositeColor": true,
              "customColor": "#000000"
            },
            "scroll": {
              "enabled": false,
              "direction": "left",
              "speedPxPerSec": 24,
              "gapPx": 32
            },
            "radius": 4,
            "snapX": null,
            "snapY": null,
            "fillOpacity": 100
          },
          "duration": {
            "visible": true,
            "x": 128,
            "y": 97,
            "w": 382,
            "h": null,
            "z": 6,
            "color": "accent",
            "fill": "color",
            "anchor": "left",
            "shadow": {
              "enabled": true,
              "blur": 4,
              "intensity": 50,
              "offsetX": 2,
              "offsetY": 2,
              "useOppositeColor": true,
              "customColor": "#000000"
            },
            "scroll": {
              "enabled": true,
              "direction": "left",
              "speedPxPerSec": 24,
              "gapPx": 32
            },
            "snapX": null,
            "snapY": null,
            "radius": 0,
            "fillOpacity": 100
          }
        },
        "switchAnim": {
          "type": "fade",
          "direction": "up",
          "durationMs": 350,
          "easing": "cubicOut"
        }
      },
      "sessionKey": null,
      "apiKey": null
    }
  }
];
