import type { WidgetConfig } from "./config";

/** One-click starter templates (ported from the original editor). */
export const PRESETS: { name: string; config: Partial<WidgetConfig> }[] = [
  {
    name: "Minimalist",
    config: {
      fallbackAccent: "#1db954",
      theme: {
        bg: "#000000CC",
        accent: "#1db954",
        autoFromArt: true,
        autoTargets: { title: false, artist: true, album: false, meta: false },
        font: "Inter",
        text: { title: "#ffffff", artist: "accent", album: "#cfcfcf", meta: "#bdbdbd", duration: "#a0a0a0" },
        textSize: { title: 30, artist: 16, album: 12, meta: 12, duration: 11 },
        textTransform: { title: "none", artist: "uppercase", album: "none", meta: "none", duration: "none" },
        textFont: { title: "Montserrat", artist: "Poppins" },
        dropShadow: {
          enabled: true,
          blur: 19,
          intensity: 15,
          offsetX: 2,
          offsetY: 2,
          useOppositeColor: true,
          customColor: "#000000",
          targets: { text: true, albumArt: true, progressBar: true, background: false },
        },
        bgEnabled: false,
      },
      layout: {
        w: 420,
        h: 130,
        showArt: true,
        align: "left",
        artSize: 68,
        artPosition: "left",
        scrollTriggerWidth: 180,
        textGap: 2,
        backgroundRadius: 16,
        artRadius: 6,
      },
      marquee: { speedPxPerSec: 24, gapPx: 32 },
      fields: {
        title: true,
        artist: true,
        album: false,
        progress: false,
        duration: false,
        history: 50,
        pausedMode: "transparent",
        pausedText: "Paused",
        durationFormat: "both",
        showDurationOnProgress: true,
        showDurationAsText: false,
      },
    } as unknown as Partial<WidgetConfig>,
  },
  {
    name: "Modern Card",
    config: {
      fallbackAccent: "#1db954",
      theme: {
        bg: "#797777",
        accent: "#1db954",
        autoFromArt: true,
        autoTargets: { title: false, artist: true, album: false, meta: false },
        font: "Inter",
        text: { title: "accent", artist: "accent", album: "#cfcfcf", meta: "#bdbdbd", duration: "accent" },
        textSize: { title: 27, artist: 18, album: 12, meta: 12, duration: 11 },
        textTransform: { title: "none", artist: "none", album: "none", meta: "none", duration: "none" },
        textFont: { title: "Poppins", artist: "Poppins", duration: "Nunito" },
        bgEnabled: true,
      },
      layout: {
        w: 310,
        h: 130,
        showArt: true,
        align: "left",
        artSize: 72,
        artPosition: "left",
        scrollTriggerWidth: 180,
        textGap: 2,
        backgroundRadius: 16,
        artRadius: 9,
        textOffset: {
          title: { x: 0, y: 3 },
          artist: { x: 0, y: -5 },
          album: { x: 0, y: 0 },
          meta: { x: 0, y: 0 },
          duration: { x: 0, y: -10 },
        },
      },
      marquee: { speedPxPerSec: 24, gapPx: 32 },
      fields: {
        title: true,
        artist: true,
        album: false,
        progress: false,
        duration: true,
        history: 50,
        pausedMode: "label",
        pausedText: "Paused",
        durationFormat: "both",
        showDurationOnProgress: true,
        showDurationAsText: true,
      },
    } as unknown as Partial<WidgetConfig>,
  },
];
